[technote]
id = "SITCOMTN-108"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-108.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-108"
github_default_branch = "main"
date_created = 2024-01-24T00:57:28Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "stable"

[[technote.authors]]
name.given = "Chris"
name.family = "Suberlak"
internal_id = "suberlakc"

[[technote.authors.affiliations]]
name = "University of Washington"
internal_id = "Washington"
address = "Dept. of Astronomy, Box 351580, Seattle, WA 98195, USA"
